
import { 
  AuditBlueprint, 
  BatchSummary, 
  FileResult, 
  ComplianceOpinion, 
  ActionPayload 
} from '../types';

/**
 * Renders a strict XHTML 1.1 compliant audit report.
 */
export function renderXhtmlReport(
  blueprint: AuditBlueprint,
  summary: BatchSummary,
  results: FileResult[],
  readinessScore: number,
  opinion: ComplianceOpinion,
  actions: ActionPayload[]
): string {
  const { company_profile } = blueprint;
  const timestamp = new Date().toISOString();

  const xhtml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <title>ESG Audit Report - ${company_profile.name}</title>
  <style type="text/css">
    body { font-family: sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; }
    h1, h2, h3 { color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
    .status-box { padding: 20px; border-radius: 8px; margin: 20px 0; border: 1px solid #cbd5e1; }
    .status-PASS { background-color: #f0fdf4; border-color: #bbf7d0; color: #166534; }
    .status-CONDITIONAL { background-color: #fffbeb; border-color: #fef3c7; color: #92400e; }
    .status-FAIL { background-color: #fef2f2; border-color: #fecaca; color: #991b1b; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { text-align: left; padding: 12px; border-bottom: 1px solid #e2e8f0; }
    th { background-color: #f8fafc; font-weight: bold; }
    .metric-val { font-family: monospace; font-weight: bold; }
    .traceability { font-size: 0.8em; color: #64748b; font-family: monospace; word-break: break-all; }
  </style>
</head>
<body>
  <h1>ESG Audit Report</h1>
  <p>Generated by <strong>AtlasChain Orchestrator</strong></p>
  
  <div class="status-box status-${opinion}">
    <h2>Audit Readiness Score: ${readinessScore.toFixed(1)}%</h2>
    <p>Compliance Opinion: <strong>${opinion}</strong></p>
    <p>Fiscal Year: ${company_profile.fiscal_year}</p>
  </div>

  <section>
    <h2>1. Company Profile</h2>
    <table>
      <tr><th>Organization</th><td>${company_profile.name}</td></tr>
      <tr><th>Industry</th><td>${company_profile.industry}</td></tr>
      <tr><th>Region</th><td>${company_profile.region}</td></tr>
      <tr><th>Regulatory Scope</th><td>${company_profile.listed ? 'Public Listing Requirement' : 'Private Disclosure'}</td></tr>
    </table>
  </section>

  <section>
    <h2>2. Audit Methodology & Frameworks</h2>
    <p>This audit was performed using the following frameworks:</p>
    <ul>
      ${blueprint.recommended_frameworks.map(f => `<li>${f}</li>`).join('')}
    </ul>
    <p>Materiality determined for ${blueprint.material_topics.length} topics.</p>
  </section>

  <section>
    <h2>3. Aggregated Disclosure Metrics</h2>
    <table>
      <thead>
        <tr>
          <th>Metric ID</th>
          <th>Aggregated Value</th>
          <th>Unit</th>
          <th>Data points</th>
        </tr>
      </thead>
      <tbody>
        ${Object.values(summary.metric_aggregates).map(m => `
          <tr>
            <td>${m.metric_id}</td>
            <td class="metric-val">${m.total.toLocaleString()}</td>
            <td>${m.unit}</td>
            <td>${m.count}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </section>

  <section>
    <h2>4. Validation Findings</h2>
    <p>Total documents processed: ${summary.total_files}</p>
    <p>Success rate: ${((summary.success_count / summary.total_files) * 100).toFixed(1)}%</p>
    ${summary.quality_summary.anomalies.length > 0 ? `
      <h3>Identified Anomalies</h3>
      <ul>
        ${summary.quality_summary.anomalies.map(a => `<li>${a}</li>`).join('')}
      </ul>
    ` : '<p>No critical anomalies detected in success-path datasets.</p>'}
  </section>

  <section>
    <h2>5. Corrective Action Plan</h2>
    <table>
      <thead>
        <tr><th>Topic</th><th>Priority</th><th>Required Action</th></tr>
      </thead>
      <tbody>
        ${actions.map(a => `
          <tr>
            <td>${a.topic}</td>
            <td><strong>${a.priority.toUpperCase()}</strong></td>
            <td>${a.description}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </section>

  <section>
    <h2>6. Traceability & Integrity</h2>
    <p>Each document is hashed and mapped to the chain of evidence. Root Traceability ID: <code>${timestamp}-${Math.random().toString(16).slice(2)}</code></p>
    <table>
      <thead>
        <tr><th>File ID</th><th>Hash</th><th>Status</th></tr>
      </thead>
      <tbody>
        ${results.map(r => `
          <tr>
            <td class="traceability">${r.file_id}</td>
            <td class="traceability">${r.hash}</td>
            <td>${r.success ? 'VERIFIED' : 'FAILED'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </section>

  <p style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 0.8em;">
    This report is machine-generated and intended for compliance review.
    Report ID: ${blueprint.id}
  </p>
</body>
</html>`;

  return xhtml;
}

/**
 * Simple in-browser XHTML validator using DOMParser.
 */
export function validateXhtml(content: string): { isValid: boolean; errors: string[] } {
  const parser = new DOMParser();
  const doc = parser.parseFromString(content, "application/xml");
  const errorNode = doc.querySelector("parsererror");
  if (errorNode) {
    return { isValid: false, errors: [errorNode.textContent || "Unknown XML parsing error"] };
  }
  return { isValid: true, errors: [] };
}
